### PR TITLE
Include Profile Data

### PR DESCRIPTION
**Pull request by JackJPowell**
This update adds your about me text as a sensor, your avatar as an image, and your playstation plus status as a binary sensor

### CODE REVIEW

**Comment by dnestico** [comment]
Sorry to comment on a PR but where is this sensor?
Screenshot 2024-12-18 at 3 20 59 PM

**Comment by JackJPowell** [comment]
Good question! This was an oversight. It is an extra attribute on the status sensor (when a game is active) but that doesn't really make sense. I'll have an update out shortly. Thanks for pointing this out!

**Comment by JackJPowell** [comment]
v0.7.1 which was just released corrects this issue. Thanks again!

**Comment by dnestico** [comment]
Nice 👍

**Pull request merged**
