### PR TITLE
Add individual sensors for each attribute

### PR DESCRIPTION
**Pull request by Levtos**
This PR extends the existing integration by adding a separate sensor for each attribute, allowing all data points to be displayed individually in Home Assistant. Please note: I haven't tested these changes yet, so additional testing might be necessary.

### CODE REVIEW

**Comment by JackJPowell** [comment]
Merged in german translation from other request.
Inspired to add optional support for exposing attributes as entities

**Comment by Hypfer** [comment]
@JackJPowell Just FYI: You might want to revert this one or at least look _very closely_ at the code.

Same AI-generated thing happened in my repo 10 Hours later:
https://github.com/Hypfer/hass-scene_presets/pull/30

**Comment by JackJPowell** [comment]
Thanks @Hypfer. Based on past discussions with him, I do think his heart is in the right place. He's just not going about things the right way.

**Comment by Levtos** [comment]
Hey @JackJPowell @Hypfer ,

I just wanted to give you a quick update on the recent changes. 

I’ve been learning programming since last year, focusing on Home Assistant and teaching myself into Python. (I have never learned to code and try to hide my insecurity about it.)

I came up with the logic and wrote the full code myself, then (probably as a mistake) used an AI tool for some tweaks to make sure everything runs perfectly. The changes that were proposed looked coherent at first glance and I took them over. Maybe I aimed for a bit too much perfection, but I wanted the code to work as reliably as possible. 

I’m sorry for any annoyance this might have caused. 😨😢

Benjamin

**Comment by JackJPowell** [comment]
Hey @Levtos, 

Don't let us get you down! It's easy to assume the worst on the internet, and you didn't deserve the attitude. There is enough negativity in the world already. I'm sorry for directing any at you. Especially someone who is legitimately trying to improve, learn a new skill, and have fun. 

On the bright side, I'm going to push out v0.6 in just a minute that includes the option to expose all the attributes as entities. You're credited in the release notes!

**Pull request closed without merging**
